AllCops:
  NewCops: enable

Style/Next:
  Enabled: false


Style/TrailingCommaInHashLiteral:
  Enabled: false

# Unless is a struggle for some of us non-ruby folks
Style/NegatedIf:
  Enabled: false

# No.
Metrics:
  Enabled: false
