AllCops:
  NewCops: enable

Style/Next:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Unless is a struggle for some of us non-ruby folks
Style/NegatedIf:
  Enabled: false
