AllCops:
  NewCops: enable

Style/Next:
  Enabled: false


Style/TrailingCommaInHashLiteral:
  Enabled: false

# Unless is a struggle for some of us non-ruby folks
Style/NegatedIf:
  Enabled: false

# No.
Metrics:
  Enabled: false

# This one is nice but we have some non-ruby-ish things that cause it to freeze
# empty hashes that are about to be modified.
#
# We don't want that. It breaks things.
Style/MutableConstant:
  Enabled: false
